### PR TITLE
Update Configuration.py

### PR DESCRIPTION
**Pull request by ServerBSvvv**
added a Russian description

### CODE REVIEW

**Comment by CrazorTheCat** [comment]
you should do a seperate file since if multiple people starts translating there will not be enough space for everything

**Comment by ServerBSvvv** [comment]
I use a translator and I didn't really understand you

**Comment by CrazorTheCat** [comment]
you should create a separate file for translation, because if multiples people starts translating, there will not be enough space for these other language.

**Comment by ServerBSvvv** [comment]
a separate instruction file? or what?

**Comment by CrazorTheCat** [comment]
yes but only with all different language for every config entry

**Comment by ServerBSvvv** [comment]
OK I'll get on it soon

**Comment by SavokBS** [comment]
2 дудки поспорили чет

**Comment by CrazorTheCat** [comment]
I will close it since there is no updates on this request

**Pull request closed without merging**
